
version: "2"
services:
    youtubedl-material-docker-rpi:
        build: .
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
        ports:
            - "8998:17442"
<<<<<<< HEAD
        image: volcan96/youtubedl-material-docker-rpi:latest
=======
        image: tzahi12345/youtubedl-material:latest
>>>>>>> 2b91293abdb845e5f93f5599d5ec3fbfa8b19f1b
