version: "2"
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: unless-stopped
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
        ports:
            - "8998:17442"
        image: volcan96/youtubedl-material-docker-rpi:3.6rev1